//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodService
    {
        public int BloodServiceId { get; set; }
        public Nullable<int> BloodId { get; set; }
        public Nullable<int> BloodUserServiceId { get; set; }
        public Nullable<decimal> BloodServiceResult { get; set; }
        public byte[] BloodServiceFinished { get; set; }
        public Nullable<bool> BloodServiceAccepted { get; set; }
        public Nullable<bool> BoolServiceStatus { get; set; }
        public Nullable<int> BoolServiceAnalyzer { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Blood Blood { get; set; }
        public virtual UserService UserService { get; set; }
    }
}
