//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurance()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int InsuranceId { get; set; }
        public string InsuranceName { get; set; }
        public string IsuranceAddress { get; set; }
        public string IsuranceInn { get; set; }
        public string InsuranceIp { get; set; }
        public string InsurancePc { get; set; }
        public string InsuranceBik { get; set; }
        public string InsuranceUserAuth { get; set; }
        public Nullable<int> InsuranceCountry { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
    }
}
