//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Blood = new HashSet<Blood>();
        }
    
        public int ParientId { get; set; }
        public string PatientFullName { get; set; }
        public string PatientLogin { get; set; }
        public string PatientPassword { get; set; }
        public string PatientGuid { get; set; }
        public string PatientEmail { get; set; }
        public string PatientSocialSecNumber { get; set; }
        public string PatientEin { get; set; }
        public Nullable<int> PatientSocialType { get; set; }
        public string PatientPhone { get; set; }
        public string PatientPassportSerial { get; set; }
        public string PatientPassportNumber { get; set; }
        public byte[] PatientBirthdate { get; set; }
        public Nullable<int> PatientInsurance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blood> Blood { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual SocialType SocialType { get; set; }
    }
}
